In [5]:
#Завдання 1. Створіть одновимірний масив (вектор) зі зростаючою геометричною прогресією, де 
#кожне наступне число більше попереднього в 2 рази, починаючи з 2, та виведіть його 
#значення
import numpy as np

start = 2
num_elements = 10  # Кількість елементів у масиві
ratio = 2

geometric_progression = start * (ratio ** np.arange(num_elements))

print("Одновимірний масив зі зростаючою геометричною прогресією:")
print(geometric_progression)

Одновимірний масив зі зростаючою геометричною прогресією:
[   2    4    8   16   32   64  128  256  512 1024]


In [7]:
#Завдання 2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненими 
#значеннями натуральних чисел, починаючи з 1, та виведіть його значення
import numpy as np

natural_numbers = np.arange(1, 10)

reciprocals = 1 / natural_numbers

matrix = reciprocals.reshape(3, 3)

print("Матриця 3x3, заповнена оберненими значеннями натуральних чисел:")
print(matrix)

Матриця 3x3, заповнена оберненими значеннями натуральних чисел:
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]


In [9]:
#Завдання 3.Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в 
#діапазоні від -3 до 3 та знайдіть максимальний елемент
import numpy as np
matrix = np.random.uniform(-3, 3, (3, 3))

max_element = np.max(matrix)

print("Масив 3x3, заповнений випадковими числами в діапазоні від -3 до 3:")
print(matrix)
print("Максимальний елемент у масиві:")
print(max_element)

Масив 3x3, заповнений випадковими числами в діапазоні від -3 до 3:
[[ 0.87755492  2.16255664 -1.84635527]
 [ 1.34269729  2.16497019 -0.60574289]
 [ 0.12837061 -0.79916623 -2.52965699]]
Максимальний елемент у масиві:
2.1649701870210523


In [11]:
#Завдання 4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в 
#діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного 
#стовпця, менших за 0.5
import numpy as np

matrix = np.random.rand(3, 3)

filtered_matrix = np.where(matrix < 0.5, matrix, 0)

column_sums = np.sum(filtered_matrix, axis=0)

print("Масив 3x3, заповнений випадковими числами в діапазоні від 0 до 1:")
print(matrix)
print("Вектор-стовпчик із сумами елементів у кожному стовпці, менших за 0.5:")
print(column_sums)

Масив 3x3, заповнений випадковими числами в діапазоні від 0 до 1:
[[0.32218409 0.58887349 0.78738553]
 [0.06082742 0.68450186 0.30237951]
 [0.67540042 0.03923259 0.5202282 ]]
Вектор-стовпчик із сумами елементів у кожному стовпці, менших за 0.5:
[0.38301151 0.03923259 0.30237951]


In [13]:
#Завдання 5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними 
#числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання 
#та множення
import numpy as np

array1 = np.random.uniform(-2, 2, 6)
array2 = np.random.uniform(-2, 2, 6)

addition = array1 + array2

subtraction = array1 - array2

multiplication = array1 * array2

print("Перший масив:")
print(array1)
print("Другий масив:")
print(array2)
print("Результат поелементного додавання:")
print(addition)
print("Результат поелементного віднімання:")
print(subtraction)
print("Результат поелементного множення:")
print(multiplication)

Перший масив:
[ 1.47125321 -1.84162877 -0.80298395 -1.84764702  0.37579467  1.91063271]
Другий масив:
[-0.12222085  1.22334384 -1.03319307  1.99733491  0.34603053  0.23253588]
Результат поелементного додавання:
[ 1.34903236 -0.61828493 -1.83617702  0.14968789  0.7218252   2.14316859]
Результат поелементного віднімання:
[ 1.59347406 -3.06497261  0.23020912 -3.84498193  0.02976415  1.67809683]
Результат поелементного множення:
[-0.17981782 -2.25294521  0.82963745 -3.69036989  0.13003643  0.44429066]


In [15]:
#Завдання 6. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 5 та 
#знайдіть їх добуток.
import numpy as np

matrix1 = np.random.randint(1, 6, (4, 4))
matrix2 = np.random.randint(1, 6, (4, 4))

product_matrix = np.dot(matrix1, matrix2)

print("Перша матриця 4x4:")
print(matrix1)
print("Друга матриця 4x4:")
print(matrix2)
print("Добуток двох матриць:")
print(product_matrix)

Перша матриця 4x4:
[[3 3 2 5]
 [3 3 3 2]
 [4 4 3 4]
 [5 3 2 3]]
Друга матриця 4x4:
[[2 1 5 2]
 [1 4 2 2]
 [3 5 2 3]
 [5 2 2 2]]
Добуток двох матриць:
[[40 35 35 28]
 [28 34 31 25]
 [41 43 42 33]
 [34 33 41 28]]


In [17]:
#Завдання 7.  Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами 
#в діапазоні від 1 до 8 та перемножте їх між собою
import numpy as np

matrix1 = np.random.randint(1, 9, (3, 2))

matrix2 = np.random.randint(1, 9, (2, 2))

product_matrix = np.dot(matrix1, matrix2)

print("Перша матриця 3x2:")
print(matrix1)
print("Друга матриця 2x2:")
print(matrix2)
print("Добуток двох матриць:")
print(product_matrix)

Перша матриця 3x2:
[[6 6]
 [6 1]
 [2 8]]
Друга матриця 2x2:
[[1 4]
 [1 7]]
Добуток двох матриць:
[[12 66]
 [ 7 31]
 [10 64]]


In [19]:
#Завдання 8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні 
#від 1 до 15 та знайдіть її обернену матрицю.
import numpy as np

matrix = np.random.randint(1, 16, (2, 2))

inverse_matrix = np.linalg.inv(matrix)

print("Початкова матриця 2x2:")
print(matrix)
print("Обернена матриця:")
print(inverse_matrix)

Початкова матриця 2x2:
[[14  4]
 [ 8  2]]
Обернена матриця:
[[-0.5  1. ]
 [ 2.  -3.5]]


In [21]:
#Завдання 9. Створіть матрицю розміром 7x3, заповніть її випадковими дійсними числами в 
#діапазоні від 0 до 1 та транспонуйте її.
import numpy as np

matrix = np.random.rand(7, 3)

transposed_matrix = np.transpose(matrix)

print("Початкова матриця 7x3:")
print(matrix)
print("Транспонована матриця 3x7:")
print(transposed_matrix)

Початкова матриця 7x3:
[[0.45615805 0.68028993 0.0769861 ]
 [0.06315682 0.57944614 0.32974596]
 [0.15439285 0.96413956 0.14923223]
 [0.59712388 0.86023606 0.94563356]
 [0.21468098 0.4345682  0.73248075]
 [0.9373659  0.52281091 0.92145456]
 [0.10307617 0.47366439 0.18306379]]
Транспонована матриця 3x7:
[[0.45615805 0.06315682 0.15439285 0.59712388 0.21468098 0.9373659
  0.10307617]
 [0.68028993 0.57944614 0.96413956 0.86023606 0.4345682  0.52281091
  0.47366439]
 [0.0769861  0.32974596 0.14923223 0.94563356 0.73248075 0.92145456
  0.18306379]]


In [23]:
#Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю 
#випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними 
#числами від 0 до 1, і знайдіть добуток матриці на вектор
import numpy as np

matrix = np.random.randint(1, 11, (3, 4))

vector = np.random.rand(4, 1)

product = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)
print("Вектор 4x1:")
print(vector)
print("Добуток матриці на вектор:")
print(product)

Матриця 3x4:
[[5 5 4 2]
 [6 5 7 8]
 [2 8 2 5]]
Вектор 4x1:
[[0.52352911]
 [0.27123552]
 [0.94071695]
 [0.77336222]]
Добуток матриці на вектор:
[[ 9.28341539]
 [17.26926868]
 [ 8.9651874 ]]


In [25]:
#Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю 
#випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами 
#від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np

matrix = np.random.rand(2, 3)

vector = np.random.rand(3, 1)

product = np.dot(matrix, vector)

print("Матриця 2x3:")
print(matrix)
print("Вектор 3x1:")
print(vector)
print("Добуток матриці на вектор:")
print(product)

Матриця 2x3:
[[0.28397106 0.55716028 0.94915801]
 [0.06945806 0.99393598 0.86318178]]
Вектор 3x1:
[[0.7392563 ]
 [0.23543014]
 [0.55998896]]
Добуток матриці на вектор:
[[0.87261772]
 [0.76872205]]


In [27]:
#Завдання 12. Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в 
#діапазоні від 1 до 10 та знайдіть їхню суму
import numpy as np

matrix1 = np.random.randint(1, 11, (6, 6))

matrix2 = np.random.randint(1, 11, (6, 6))

sum_matrix = matrix1 + matrix2

print("Перша матриця 6x6:")
print(matrix1)
print("Друга матриця 6x6:")
print(matrix2)
print("Сума двох матриць:")
print(sum_matrix)

Перша матриця 6x6:
[[ 8  3  3  9  1  6]
 [ 7  7  2  1  9  1]
 [ 4  6  9  2  4  1]
 [ 9  6  8  5  6  6]
 [ 8  7  8  8 10  6]
 [ 7  4  5  3  4  5]]
Друга матриця 6x6:
[[ 4  1  2  8  3  4]
 [ 1  7  4  3  5  1]
 [ 5  8  2 10  5  9]
 [ 5  7  3  9  4  4]
 [ 9 10  4  8  9 10]
 [ 4 10  5  6  9  7]]
Сума двох матриць:
[[12  4  5 17  4 10]
 [ 8 14  6  4 14  2]
 [ 9 14 11 12  9 10]
 [14 13 11 14 10 10]
 [17 17 12 16 19 16]
 [11 14 10  9 13 12]]


In [29]:
#Завдання 13.Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в 
#діапазоні від 0 до 1 та знайдіть добуток їх елементів.
import numpy as np

matrix1 = np.random.rand(3, 3)

matrix2 = np.random.rand(3, 3)

product_matrix1 = np.prod(matrix1)
product_matrix2 = np.prod(matrix2)

print("Перша матриця 3x3:")
print(matrix1)
print("Добуток елементів першої матриці:")
print(product_matrix1)

print("\nДруга матриця 3x3:")
print(matrix2)
print("Добуток елементів другої матриці:")
print(product_matrix2)

Перша матриця 3x3:
[[0.72179113 0.97403231 0.7195481 ]
 [0.27117283 0.64069977 0.53883951]
 [0.15659801 0.02743305 0.62624577]]
Добуток елементів першої матриці:
0.00012741192199674725

Друга матриця 3x3:
[[0.95670892 0.95448036 0.94973715]
 [0.01554786 0.70465924 0.43453284]
 [0.48676536 0.40385707 0.20081265]]
Добуток елементів другої матриці:
0.00016299005939789902


In [31]:
#Завдання 14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в 
#діапазоні від -5 до 5 та знайдіть суму елементів матриці, які більше за їх середнє 
#арифметичне значення.
import numpy as np

matrix = np.random.uniform(-5, 5, (3, 3))

mean_value = np.mean(matrix)

greater_than_mean = matrix[matrix > mean_value]

sum_greater_than_mean = np.sum(greater_than_mean)

print("Матриця 3x3:")
print(matrix)
print("Середнє арифметичне значення матриці:")
print(mean_value)
print("Сума елементів, які більші за середнє арифметичне:")
print(sum_greater_than_mean)

Матриця 3x3:
[[ 2.60938125  3.38908964 -0.97818809]
 [ 4.1758222  -4.69123992  0.7358182 ]
 [-4.79914578  2.54662173  2.47969423]]
Середнє арифметичне значення матриці:
0.6075392725823905
Сума елементів, які більші за середнє арифметичне:
15.936427244300832


In [33]:
#Завдання 15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в 
#діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найменше ціле значення 
#в кожному рядку матриці.
import numpy as np

matrix = np.random.rand(3, 3)

min_integers = np.floor(matrix).astype(int)  # Перетворюємо на ціле число, округлюючи вниз
min_values_per_row = np.min(min_integers, axis=1)  # Знаходимо мінімальне значення в кожному рядку

min_values_column = min_values_per_row.reshape(-1, 1)

print("Матриця 3x3:")
print(matrix)
print("Вектор-стовпчик, що містить найменше ціле значення в кожному рядку:")
print(min_values_column)

Матриця 3x3:
[[0.17852266 0.99303662 0.33062215]
 [0.91682739 0.88728215 0.84771062]
 [0.46267051 0.16531014 0.07770651]]
Вектор-стовпчик, що містить найменше ціле значення в кожному рядку:
[[0]
 [0]
 [0]]


In [ ]:
#Висновок: ми навчилися 